---
language: ruby

sudo: required

cache:
    - bundler

rvm:
    - 2.3.0

gemfile: ./ci/Gemfile.ci

env:
  - DOCKER_VERSION=1.9.1
  - DOCKER_VERSION=1.10.3
  - DOCKER_VERSION=1.11.2

services:
    - docker

branches:
    only:
        - master
        - dev

before_install: ./ci/install_dependencies.sh

before_script:
    - export PATH=/opt/docker:$PATH
    - docker version

script: "bundle exec rspec ./Dockspec.rb"