---
language: ruby

cache:
    - bundler

sudo: false

rvm:
    - 2.3.0

gemfile: tests/Gemfile.ci

env:
  - DOCKER_VERSION=1.9.1
  - DOCKER_VERSION=1.10.2

services:
    - docker

branches:
    only:
        - master

before_install: ./tests/install_dependencies.sh

before_script:
    - export PATH=/opt/docker:$PATH
    - docker version

script: "bundle exec rspec tests/Dockspec.rb"