---
language: ruby

sudo: required

cache:
  - bundler

rvm:
  - 2.3.1

gemfile: ./ci/Gemfile.ci

env:
  - DOCKER_VERSION=1.13.1

services:
  - docker

branches:
  only:
    - master


before_script:
  - export PATH=/opt/docker:$PATH
  - docker version

script: "bundle exec rspec ./Dockspec.rb"